In [31]:
import pandas as pd
import numpy as np

# Create the superhero dataset
data = {
    "Superhero Name": [
        "Iron Phantom", 
        "Fire Falcon", 
        "Aqua Guardian", 
        "Tech Wizard", 
        "Thunder Streak", 
        "Mystic Shield", 
        "Earth Titan", 
        "Shadow Striker", 
        "Mind Bender", 
        "Frost Queen"
    ],
    "Age": [35, 28, 30, 40, 25, 32, 45, 29, 38, 27],
    "Power": [
        "Invisibility", 
        "Pyrokinesis", 
        "Hydrokinetics", 
        "Tech Manipulation", 
        "Super Speed", 
        "Teleportation", 
        "Geokinesis", 
        "Shadow Manipulation", 
        "Telepathy", 
        "Cryokinesis"
    ],
    "City": [
        "Metropolis", 
        "Gotham", 
        "Atlantis", 
        "Silicon Valley", 
        "New York", 
        "Mystic Falls", 
        "Rocky Hills", 
        "Shadow City", 
        "Dreamland", 
        "Snowy Peaks"
    ],
    "Sidekick": [
        "Shadow Hawk", 
        "Blaze", 
        np.nan, 
        "Byte", 
        "Lightning Bug", 
        "Phantom", 
        "Stone Guardian", 
        np.nan, 
        "Dream Weaver", 
        "Ice Prince"
    ],
    "Strength": [95, 85, 90, 70, 80, 75, 100, 88, 60, 78],
    "Weakness": [
        "Loud Noises", 
        "Water", 
        "Drought", 
        "EMP", 
        "Slowness", 
        np.nan, 
        "Water", 
        "Bright Light", 
        "Mental Blocks", 
        "Heat"
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

   Superhero Name  Age                Power            City        Sidekick  \
0    Iron Phantom   35         Invisibility      Metropolis     Shadow Hawk
1     Fire Falcon   28          Pyrokinesis          Gotham           Blaze
2   Aqua Guardian   30        Hydrokinetics        Atlantis             NaN
3     Tech Wizard   40    Tech Manipulation  Silicon Valley            Byte
4  Thunder Streak   25          Super Speed        New York   Lightning Bug
5   Mystic Shield   32        Teleportation    Mystic Falls         Phantom
6     Earth Titan   45           Geokinesis     Rocky Hills  Stone Guardian
7  Shadow Striker   29  Shadow Manipulation     Shadow City             NaN
8     Mind Bender   38            Telepathy       Dreamland    Dream Weaver
9     Frost Queen   27          Cryokinesis     Snowy Peaks      Ice Prince

   Strength       Weakness
0        95    Loud Noises
1        85          Water
2        90        Drought
3        70            EMP
4        80       Slowness
5        75            NaN
6       100          Water
7        88   Bright Light
8        60  Mental Blocks
9        78           Heat

In [32]:
df.loc[df['Age']>=30,"Experience Level"]="Senior"
df.loc[df['Age']<30,"Experience Level"]="Junior"
#superhero_df['Experience Level'] = superhero_df['Age'].apply(lambda x: 'Junior' if x < 30 else 'Senior')

In [21]:
df = df.drop(columns=['Weakness'])

In [33]:
df[df['Strength']>80]

,Superhero Name,Age,Power,City,Sidekick,Strength,Weakness,Experience Level
0,Iron Phantom,35,Invisibility,Metropolis,Shadow Hawk,95,Loud Noises,Senior
1,Fire Falcon,28,Pyrokinesis,Gotham,Blaze,85,Water,Junior
2,Aqua Guardian,30,Hydrokinetics,Atlantis,NaN,90,Drought,Senior
6,Earth Titan,45,Geokinesis,Rocky Hills,Stone Guardian,100,Water,Senior
7,Shadow Striker,29,Shadow Manipulation,Shadow City,NaN,88,Bright Light,Junior

In [35]:
# Replacing NA values
df['Sidekick'] = df['Sidekick'].fillna('None')
df['Weakness'] = df['Weakness'].fillna('Unknown')

In [36]:
df

,Superhero Name,Age,Power,City,Sidekick,Strength,Weakness,Experience Level
0,Iron Phantom,35,Invisibility,Metropolis,Shadow Hawk,95,Loud Noises,Senior
1,Fire Falcon,28,Pyrokinesis,Gotham,Blaze,85,Water,Junior
2,Aqua Guardian,30,Hydrokinetics,Atlantis,None,90,Drought,Senior
3,Tech Wizard,40,Tech Manipulation,Silicon Valley,Byte,70,EMP,Senior
4,Thunder Streak,25,Super Speed,New York,Lightning Bug,80,Slowness,Junior
5,Mystic Shield,32,Teleportation,Mystic Falls,Phantom,75,Unknown,Senior
6,Earth Titan,45,Geokinesis,Rocky Hills,Stone Guardian,100,Water,Senior
7,Shadow Striker,29,Shadow Manipulation,Shadow City,None,88,Bright Light,Junior
8,Mind Bender,38,Telepathy,Dreamland,Dream Weaver,60,Mental Blocks,Senior
9,Frost Queen,27,Cryokinesis,Snowy Peaks,Ice Prince,78,Heat,Junior